#include <iostream>
using namespace std;

void last()
{
	cout << "Last" << endl;  // ðŸ’› 5 ðŸ’›
	cout << "Throws exception" << endl;  // ðŸ’› 6 ðŸ’›

	throw 'a';
	cout << "End Last" << endl; // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
}

void third()
{
	cout << "Third" << endl; // ðŸ’› 4 ðŸ’›

	last();

	cout << "End third" << endl;  // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
}

void second()
{
	cout << "Second" << endl; // ðŸ’› 3 ðŸ’›

	try
	{
		third();
	}
	catch (double)
	{
		std::cerr << "Second caught double exception!" << endl;  // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
	}
	cout << "End second" << endl;  // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
}

void first()
{
	cout << "First" << endl;  // ðŸ’› 2 ðŸ’›

	try
	{
		second();
	}
	catch (double)
	{
		std::cerr << "first caught int exception!" << endl; // ðŸ’› 7 ðŸ’›
	}
	cout << "End first" << endl; // ðŸ’› 8 ðŸ’›
}

int main()
{
	cout << "Start" << endl;  // ðŸ’› 1 ðŸ’›

	try
	{
		first(); 
	}
	catch (double)
	{
		std::cerr << "main caught int exception!" << endl;  // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
	}
	//uncaught exception

    catch (...) //catch-all-handlers
	{
		std::cerr << "main caught ellipses exception!" << endl;  // ðŸŸ¦ ì‹¤í–‰ X ðŸŸ¦
	}
	cout << "End of main" << endl; // ðŸ’› 9 ðŸ’›
}